In [1]:
import numpy as np

In [4]:
# Intialize 5X5 dimensions array with all Zeros
first = np.zeros((5,5))

In [5]:
first

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# Initialize the array with 10 to 100 with step of 5
second = np.arange(10, 100, 5)

In [7]:
second

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [16]:
# Create a 2D array with the value of (10, 20, 30, 40, 50, 60) and set the dimention of 2*3
# 1. Print the number of element in the array
# 2. Get the datatype of the array

third = np.array([(10,20,30),(40,50,60)])
len(third) 
type(third)

numpy.ndarray

In [19]:
# Create the numpy array with (1,2,3) and another is (4, 5, 6)
# Then perform arithematic operations : Additin, Subtraction, Mulplication, Division

first = np.array([1, 2, 3])
second = np.array([4, 5, 6])
first, second

(array([1, 2, 3]), array([4, 5, 6]))

In [21]:
sum = first+second
sum

array([5, 7, 9])

In [23]:
sub = first-second
sub

array([-3, -3, -3])

In [25]:
mul = first*second
mul

array([ 4, 10, 18])

In [26]:
div = first/second
div

array([0.25, 0.4 , 0.5 ])

In [70]:
# Next Assignment
arr = np.arange(10, 100, 10)
arr = arr.reshape(3, 3)

In [71]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
arr[1:2] # Solution of Second

array([[40, 50, 60]])

In [75]:
arr[0:3, 2] #Solution of first 

array([30, 60, 90])

In [87]:
arr[0:2 , 0:2] #Solution of third

array([[10, 20],
       [40, 50]])